# /agent/managers/db.py, updated 2025-07-26 15:30 EEST
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.engine import URL
from lib.basic_logger import BasicLogger
import globals
import os
import toml

log = globals.get_logger("db")

class Database:
    _instance = None

    @classmethod
    def get_database(cls):
        if cls._instance is None:
            cls._instance = Database()
        return cls._instance

    def __init__(self):
        self.engine = create_engine(self._build_db_url(), echo=False)
        self._init_tables()
        log.info("Инициализирована БД: %s", str(self.engine.url))

    @staticmethod
    def _load_runtime_config() -> dict:
        cfg_file = globals.CONFIG_FILE
        if not cfg_file or not os.path.exists(cfg_file):
            return {}
        try:
            return toml.load(cfg_file)
        except Exception as e:
            log.warn("Не удалось загрузить конфиг %s: %s", cfg_file, str(e))
            return {}

    @staticmethod
    def _load_secret_value(secret_file: str) -> str | None:
        if not secret_file:
            return None
        if not os.path.exists(secret_file):
            return None
        try:
            with open(secret_file, "r", encoding="utf-8") as f:
                return f.read().strip() or None
        except Exception as e:
            log.warn("Не удалось прочитать secret file %s: %s", secret_file, str(e))
            return None

    def _build_db_url(self) -> str:
        cfg = self._load_runtime_config().get("database", {})
        backend = os.getenv("DB_BACKEND", cfg.get("backend", "sqlite")).strip().lower()

        has_pg_env = any(os.getenv(k) for k in ("PGHOST", "PGUSER", "PGDATABASE"))
        if backend == "postgres" or has_pg_env:
            pg_host = os.getenv("PGHOST", cfg.get("host", "postgres"))
            pg_port = int(os.getenv("PGPORT", str(cfg.get("port", 5432))))
            pg_user = os.getenv("PGUSER", cfg.get("user", "cqds"))
            pg_db = os.getenv("PGDATABASE", cfg.get("database", "cqds"))

            secret_file = os.getenv("PGPASSWORD_FILE", cfg.get("password_file", "/run/secrets/cqds_db_password"))
            pg_password = os.getenv("PGPASSWORD") or self._load_secret_value(secret_file) or cfg.get("password")
            if not pg_password:
                raise RuntimeError(
                    "PostgreSQL password is not set. Use PGPASSWORD or PGPASSWORD_FILE (or [database].password in config)."
                )

            return URL.create(
                "postgresql+psycopg2",
                username=pg_user,
                password=pg_password,
                host=pg_host,
                port=pg_port,
                database=pg_db,
            ).render_as_string(hide_password=False)

        sqlite_path = os.getenv("SQLITE_PATH", cfg.get("sqlite_path", "/app/data/multichat.db"))
        return f"sqlite:///{sqlite_path}"

    def is_postgres(self) -> bool:
        return self.engine.url.get_backend_name().startswith("postgresql")

    def _init_tables(self):
        if self.is_postgres():
            self.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_name TEXT,
                    llm_class TEXT,
                    llm_token TEXT,
                    tokens_limit BIGINT DEFAULT 131072,
                    tokens_input_cost DOUBLE PRECISION,
                    tokens_output_cost DOUBLE PRECISION,
                    llm_reasoning_eff TEXT DEFAULT 'medium',
                    password_hash TEXT,
                    salt TEXT
                )
            """)
            self.execute("""
                CREATE TABLE IF NOT EXISTS user_settings (
                    user_id BIGINT PRIMARY KEY,
                    search_mode TEXT DEFAULT 'auto',
                    search_sources TEXT DEFAULT '["web","x","news","rss"]',
                    max_search_results BIGINT DEFAULT 20,
                    from_date TEXT,
                    to_date TEXT,
                    FOREIGN KEY (user_id) REFERENCES users(user_id)
                )
            """)
            self.execute("""
                CREATE TABLE IF NOT EXISTS scheduled_jobs (
                    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL UNIQUE,
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    cron_expr TEXT NOT NULL,
                    timezone TEXT NOT NULL DEFAULT 'UTC',
                    kind TEXT NOT NULL,
                    config_json TEXT NOT NULL DEFAULT '{}',
                    miss_after_sec INTEGER NOT NULL DEFAULT 93600,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """)
            self.execute("""
                CREATE TABLE IF NOT EXISTS scheduled_job_runs (
                    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id BIGINT NOT NULL REFERENCES scheduled_jobs(job_id),
                    started_at TIMESTAMPTZ NOT NULL,
                    finished_at TIMESTAMPTZ,
                    status TEXT NOT NULL,
                    exit_code INTEGER,
                    stdout_tail TEXT,
                    stderr_tail TEXT,
                    trigger_kind TEXT NOT NULL DEFAULT 'scheduled'
                )
            """)
            self.execute(
                "CREATE INDEX IF NOT EXISTS idx_scheduled_job_runs_job_finished "
                "ON scheduled_job_runs (job_id, finished_at DESC)"
            )
            self.execute("""
                CREATE TABLE IF NOT EXISTS config (
                    entry_key TEXT PRIMARY KEY,
                    entry_value TEXT,
                    entry_fallback TEXT
                )
            """)
            return

        self.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_name TEXT,
                llm_class TEXT,
                llm_token TEXT,
                tokens_limit INTEGER DEFAULT 131072,
                tokens_input_cost FLOAT,
                tokens_output_cost FLOAT,
                llm_reasoning_eff TEXT DEFAULT 'medium',
                password_hash TEXT,
                salt TEXT
            )
        """)
        self.execute("""
            CREATE TABLE IF NOT EXISTS user_settings (
                user_id INTEGER PRIMARY KEY,
                search_mode TEXT DEFAULT 'auto',
                search_sources TEXT DEFAULT '["web","x","news","rss"]',
                max_search_results INTEGER DEFAULT 20,
                from_date TEXT,
                to_date TEXT,
                FOREIGN KEY (user_id) REFERENCES users(user_id)
            )
        """)
        self.execute("""
            CREATE TABLE IF NOT EXISTS scheduled_jobs (
                job_id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE,
                enabled INTEGER NOT NULL DEFAULT 1,
                cron_expr TEXT NOT NULL,
                timezone TEXT NOT NULL DEFAULT 'UTC',
                kind TEXT NOT NULL,
                config_json TEXT NOT NULL DEFAULT '{}',
                miss_after_sec INTEGER NOT NULL DEFAULT 93600,
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                updated_at TEXT NOT NULL DEFAULT (datetime('now'))
            )
        """)
        self.execute("""
            CREATE TABLE IF NOT EXISTS scheduled_job_runs (
                run_id INTEGER PRIMARY KEY AUTOINCREMENT,
                job_id INTEGER NOT NULL,
                started_at TEXT NOT NULL,
                finished_at TEXT,
                status TEXT NOT NULL,
                exit_code INTEGER,
                stdout_tail TEXT,
                stderr_tail TEXT,
                trigger_kind TEXT NOT NULL DEFAULT 'scheduled',
                FOREIGN KEY (job_id) REFERENCES scheduled_jobs(job_id)
            )
        """)
        self.execute(
            "CREATE INDEX IF NOT EXISTS idx_scheduled_job_runs_job_finished "
            "ON scheduled_job_runs (job_id, finished_at DESC)"
        )
        self.execute("""
            CREATE TABLE IF NOT EXISTS config (
                entry_key TEXT PRIMARY KEY,
                entry_value TEXT,
                entry_fallback TEXT
            )
        """)

    def execute(self, query, params=None):
        try:
            with self.engine.connect() as conn:
                params = params if params is not None else {}
                result = conn.execute(text(query), params)
                conn.commit()
                return result
        except SQLAlchemyError as e:
            log.excpt("Ошибка выполнения запроса: %s, params=~%s, error=%s",
                      query[:50] + "..." if len(query) > 50 else query, str(params), str(e))
            raise

    def fetch_one(self, query, params=None):
        try:
            with self.engine.connect() as conn:
                params = params if params is not None else {}
                result = conn.execute(text(query), params)
                row = result.fetchone()
                conn.commit()
                return row
        except SQLAlchemyError as e:
            log.excpt("Ошибка fetch_one: %s, params=~%s, error=%s",
                      query[:50] + "..." if len(query) > 50 else query, str(params), str(e))
            raise

    def fetch_all(self, query, params=None):
        try:
            with self.engine.connect() as conn:
                params = params if params is not None else {}
                result = conn.execute(text(query), params)
                try:
                    rows = result.fetchall()
                except Exception:
                    rows = []  # DDL/DML statements that don't return rows
                conn.commit()
                return rows
        except SQLAlchemyError as e:
            log.excpt("Ошибка fetch_all: %s, params=~%s, error=%s",
                      query[:50] + "..." if len(query) > 50 else query, str(params), str(e))
            raise


class DataTable:
    def __init__(self, table_name: str, template: list):
        self.db = Database.get_database()
        self.table_name = table_name
        self.template = template
        self.create()
        self.upgrade()

    def create(self):
        try:
            fields = ", ".join(self._normalized_template())
            query = f"CREATE TABLE IF NOT EXISTS {self.table_name} ({fields})"
            self.db.execute(query)
            log.debug("Таблица %s создана или уже существует", self.table_name)
        except Exception as e:
            log.excpt("Не удалось создать таблицу %s: %s", self.table_name, str(e))
            raise

    def _normalized_template(self):
        if not self.db.is_postgres():
            return self.template
        result = []
        for field in self.template:
            upper = field.upper().strip()
            if upper.startswith("FOREIGN KEY"):
                continue
            normalized = field
            if "INTEGER PRIMARY KEY AUTOINCREMENT" in field:
                normalized = field.replace(
                    "INTEGER PRIMARY KEY AUTOINCREMENT",
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                )
            normalized = normalized.replace(" BLOB", " BYTEA")
            normalized = normalized.replace(" FLOAT", " DOUBLE PRECISION")
            result.append(normalized)
        return result

    def _primary_key_column(self):
        cols = self._primary_key_columns()
        return cols[0] if cols else None

    def _primary_key_columns(self):
        inline_pk = []
        for field in self.template:
            upper = field.upper().strip()
            if upper.startswith("PRIMARY KEY"):
                left = field.find('(')
                right = field.rfind(')')
                if left != -1 and right != -1 and right > left:
                    raw = field[left + 1:right]
                    cols = [c.strip() for c in raw.split(',') if c.strip()]
                    if cols:
                        return cols
                continue
            if "PRIMARY KEY" in upper and not upper.startswith("FOREIGN"):
                inline_pk.append(field.split()[0])
        return inline_pk

    def upgrade(self):
        try:
            if self.db.is_postgres():
                current_columns = self.db.fetch_all(
                    """
                    SELECT column_name
                    FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = :table_name
                    """,
                    {"table_name": self.table_name}
                )
                current_column_names = {row[0] for row in current_columns}
            else:
                current_columns = self.db.fetch_all(f"PRAGMA table_info({self.table_name})")
                current_column_names = {row[1] for row in current_columns}
            template_columns = set()
            for field in self._normalized_template():
                column_name = field.split()[0]
                if column_name not in ('PRIMARY', 'FOREIGN'):
                    template_columns.add(column_name)
            missing_columns = []
            for field in self._normalized_template():
                column_name = field.split()[0]
                if column_name not in current_column_names and column_name not in ('PRIMARY', 'FOREIGN'):
                    missing_columns.append(field)
            for column_def in missing_columns:
                query = f"ALTER TABLE {self.table_name} ADD COLUMN {column_def}"
                self.db.execute(query)
                log.debug("Добавлен столбец %s в таблицу %s", column_def.split()[0], self.table_name)
            if not missing_columns:
                log.debug("Таблица %s актуальна", self.table_name)
        except Exception as e:
            log.excpt("Не удалось обновить таблицу %s: %s", self.table_name, str(e))
            raise

    def insert_into(self, values: dict, ignore: bool = False):
        try:
            fields = ", ".join(values.keys())
            placeholders = ", ".join([f":{key}" for key in values.keys()])
            if self.db.is_postgres():
                query = f"INSERT INTO {self.table_name} ({fields}) VALUES ({placeholders})"
                if ignore:
                    query += " ON CONFLICT DO NOTHING"
                    self.db.execute(query, values)
                    return None
                pk = self._primary_key_column()
                if pk:
                    query += f" RETURNING {pk}"
                    row = self.db.fetch_one(query, values)
                    return row[0] if row else None
                self.db.execute(query, values)
                return None

            insert_type = "INSERT OR IGNORE" if ignore else "INSERT"
            query = f"{insert_type} INTO {self.table_name} ({fields}) VALUES ({placeholders})"
            self.db.execute(query, values)
            return self.db.fetch_one(f"SELECT last_insert_rowid()")[0]
        except Exception as e:
            log.excpt("Не удалось вставить в %s: %s", self.table_name, str(e))
            raise

    def insert_or_replace(self, values: dict):
        try:
            fields = ", ".join(values.keys())
            placeholders = ", ".join([f":{key}" for key in values.keys()])
            if self.db.is_postgres():
                pk_cols = self._primary_key_columns()
                if not pk_cols:
                    raise ValueError(f"insert_or_replace for {self.table_name} requires primary key")
                missing = [pk for pk in pk_cols if pk not in values]
                if missing:
                    raise ValueError(
                        f"insert_or_replace for {self.table_name} requires {', '.join(missing)} in values"
                    )

                set_expr = ", ".join([f"{k} = EXCLUDED.{k}" for k in values.keys() if k not in pk_cols])
                query = f"INSERT INTO {self.table_name} ({fields}) VALUES ({placeholders})"
                conflict_cols = ", ".join(pk_cols)
                if set_expr:
                    query += f" ON CONFLICT ({conflict_cols}) DO UPDATE SET {set_expr}"
                else:
                    query += f" ON CONFLICT ({conflict_cols}) DO NOTHING"

                returning_pk = pk_cols[0]
                query += f" RETURNING {returning_pk}"
                row = self.db.fetch_one(query, values)
                return row[0] if row else values.get(returning_pk)

            query = f"INSERT OR REPLACE INTO {self.table_name} ({fields}) VALUES ({placeholders})"
            self.db.execute(query, values)
            return self.db.fetch_one(f"SELECT last_insert_rowid()")[0]
        except Exception as e:
            log.excpt("Не удалось вставить или заменить в %s: %s", self.table_name, str(e))
            raise

    def update(self, values: dict, conditions: dict):
        try:
            set_clause = ", ".join([f"{key} = :{key}" for key in values.keys()])
            conditions_clause = " AND ".join([f"{key} = :cond_{key}" for key in conditions.keys()])
            query = f"UPDATE {self.table_name} SET {set_clause} WHERE {conditions_clause}"
            params = {**values, **{f"cond_{key}": value for key, value in conditions.items()}}
            self.db.execute(query, params)
            log.debug("Обновлено %s: values=~%s, conditions=~%s", self.table_name, str(values), str(conditions))
        except Exception as e:
            log.excpt("Не удалось обновить %s: %s", self.table_name, str(e))
            raise

    def delete_from(self, conditions: dict):
        try:
            conditions_clause = " AND ".join([f"{key} = :{key}" for key in conditions.keys()])
            query = f"DELETE FROM {self.table_name} WHERE {conditions_clause}"
            params = conditions
            result = self.db.execute(query, params)
            log.debug("Удалено из %s: conditions=~%s", self.table_name, str(conditions))
            return result
        except Exception as e:
            log.excpt("Не удалось удалить из %s: %s", self.table_name, str(e))
            raise

    def select_from(self, columns: list = None, conditions=None, order_by: str = None,
                    limit: int = None, joins: list = None, fetch_all: bool = True):
        try:
            columns_str = ", ".join(columns) if columns else '*'
            query = f"SELECT {columns_str} FROM {self.table_name} p"
            params = {}
            if joins:
                for join in joins:
                    table, alias, condition = join
                    query += f" JOIN {table} {alias} ON {condition}"
            if conditions:
                if isinstance(conditions, str):
                    query += f" WHERE {conditions}"
                elif isinstance(conditions, list):
                    conditions_list = []
                    for cond in conditions:
                        if isinstance(cond, tuple) and len(cond) == 3:
                            key, op, value = cond
                            if op == 'IN' and isinstance(value, (list, tuple)):
                                pc = []
                                for i, val in enumerate(value):
                                    ik = f"{key}_{i}"
                                    params[ik] = val
                                    pc.append(f':{ik}')
                                conditions_list.append(f"p.{key} IN ({', '.join(pc)})")
                            else:
                                conditions_list.append(f"p.{key} {op} :{key}")
                                params[key] = value
                        else:
                            raise ValueError(f"Invalid condition format: {cond}")
                    if conditions_list:
                        conditions_str = " AND ".join(conditions_list)
                        query += f" WHERE {conditions_str}"
                else:
                    conditions_list = []
                    for key, value in conditions.items():
                        conditions_list.append(f"p.{key} = :{key}")
                        params[key] = value
                    if conditions_list:
                        conditions_str = " AND ".join(conditions_list)
                        query += f" WHERE {conditions_str}"
            if order_by:
                query += f" ORDER BY {order_by}"
            if limit:
                query += f" LIMIT {limit}"
            db = self.db
            if fetch_all:
                result = db.fetch_all(query, params)
            else:
                result = db.fetch_one(query, params)
            return result
        except Exception as e:
            log.excpt("Не удалось выполнить выборку %s: ", query[:50] + "..." if len(query) > 50 else query, e=e)
            raise

    def select_row(self, columns: list = None, conditions=None, order_by: str = None, joins: list = None):
        return self.select_from(columns, conditions, order_by, limit=1, joins=joins, fetch_all=False)