import os
import sqlite3
import sys
import time

import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_values


def log(msg: str) -> None:
    print(f"[sqlite->pg] {msg}")


def resolve_pg_password() -> str:
    pwd = os.getenv("PGPASSWORD", "")
    if pwd:
        return pwd

    pwd_file = os.getenv("PGPASSWORD_FILE", "/run/secrets/cqds_db_password")
    if pwd_file and os.path.exists(pwd_file):
        with open(pwd_file, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""


def map_sqlite_type(type_name: str) -> str:
    t = (type_name or "").upper()
    if "INT" in t:
        return "BIGINT"
    if any(x in t for x in ("CHAR", "CLOB", "TEXT")):
        return "TEXT"
    if "BLOB" in t:
        return "BYTEA"
    if any(x in t for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BOOL" in t:
        return "BOOLEAN"
    return "NUMERIC"


def wait_postgres(max_retries: int = 30, delay_s: int = 2):
    pg_password = resolve_pg_password()
    for attempt in range(1, max_retries + 1):
        try:
            conn = psycopg2.connect(
                host=os.getenv("PGHOST", "postgres"),
                port=int(os.getenv("PGPORT", "5432")),
                dbname=os.getenv("PGDATABASE", "cqds"),
                user=os.getenv("PGUSER", "cqds"),
                password=pg_password,
            )
            conn.autocommit = False
            return conn
        except Exception as e:
            log(f"postgres not ready (attempt {attempt}/{max_retries}): {e}")
            time.sleep(delay_s)
    raise RuntimeError("postgres is not reachable")


def migrate_table(pg_conn, sqlite_conn, table_name: str) -> None:
    s_cur = sqlite_conn.cursor()
    p_cur = pg_conn.cursor()

    s_cur.execute(f'PRAGMA table_info("{table_name}")')
    cols = s_cur.fetchall()
    if not cols:
        log(f"skip table {table_name}: no columns")
        return

    # PRAGMA columns: cid, name, type, notnull, dflt_value, pk
    pk_cols = [c[1] for c in sorted(cols, key=lambda x: x[5]) if c[5] > 0]

    col_defs = []
    single_int_identity = False
    for _, name, ctype, notnull, default_val, _pk in cols:
        pg_type = map_sqlite_type(ctype)
        is_single_int_pk = len(pk_cols) == 1 and pk_cols[0] == name and pg_type == "BIGINT"
        if is_single_int_pk:
            single_int_identity = True
            definition = sql.SQL("{} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").format(sql.Identifier(name))
        else:
            default_sql = sql.SQL("")
            if default_val is not None:
                default_sql = sql.SQL(" DEFAULT {}".format(default_val))
            definition = sql.SQL("{} {}{}").format(
                sql.Identifier(name),
                sql.SQL(pg_type),
                default_sql + (sql.SQL(" NOT NULL") if notnull else sql.SQL("")),
            )
        col_defs.append(definition)

    if pk_cols and not single_int_identity:
        col_defs.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(sql.Identifier(c) for c in pk_cols)
            )
        )

    create_query = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
        sql.Identifier(table_name),
        sql.SQL(", ").join(col_defs),
    )
    p_cur.execute(create_query)

    # If table already existed in PostgreSQL (from previous runs), ensure schema catches up.
    p_cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table_name,),
    )
    existing_cols = {r[0] for r in p_cur.fetchall()}
    for _, name, ctype, notnull, default_val, _pk in cols:
        if name in existing_cols:
            continue
        pg_type = map_sqlite_type(ctype)
        default_sql = sql.SQL("")
        if default_val is not None:
            default_sql = sql.SQL(" DEFAULT {}".format(default_val))
        alter_query = sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS {} {}{}{}").format(
            sql.Identifier(table_name),
            sql.Identifier(name),
            sql.SQL(pg_type),
            default_sql,
            sql.SQL(" NOT NULL") if notnull else sql.SQL(""),
        )
        p_cur.execute(alter_query)
        log(f"table {table_name}: added missing column {name} ({pg_type})")

    s_cur.execute(f'SELECT * FROM "{table_name}"')
    rows = s_cur.fetchall()
    if not rows:
        pg_conn.commit()
        log(f"table {table_name}: no rows")
        return

    col_names = [c[1] for c in cols]
    insert_base = sql.SQL("INSERT INTO {} ({}) VALUES %s").format(
        sql.Identifier(table_name),
        sql.SQL(", ").join(sql.Identifier(c) for c in col_names),
    )
    if pk_cols:
        insert_query = insert_base + sql.SQL(" ON CONFLICT ({}) DO NOTHING").format(
            sql.SQL(", ").join(sql.Identifier(c) for c in pk_cols)
        )
    else:
        insert_query = insert_base

    execute_values(p_cur, insert_query.as_string(pg_conn), rows, page_size=1000)
    pg_conn.commit()
    log(f"table {table_name}: migrated {len(rows)} rows")


def sync_postgres_sequences(pg_conn) -> None:
    p_cur = pg_conn.cursor()
    p_cur.execute(
        """
        SELECT c.table_name, c.column_name,
               pg_get_serial_sequence(format('%I.%I', c.table_schema, c.table_name), c.column_name) AS seq_name
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND pg_get_serial_sequence(format('%I.%I', c.table_schema, c.table_name), c.column_name) IS NOT NULL
        ORDER BY c.table_name, c.ordinal_position
        """
    )
    rows = p_cur.fetchall()
    for table_name, column_name, seq_name in rows:
        if not seq_name:
            continue
        p_cur.execute(
            sql.SQL("SELECT setval(%s, COALESCE((SELECT MAX({}) FROM {}), 0) + 1, false)").format(
                sql.Identifier(column_name),
                sql.Identifier(table_name),
            ),
            (seq_name,),
        )
    log(f"sequences synced: {len(rows)}")


def main() -> int:
    sqlite_path = os.getenv("SQLITE_PATH", "/app/data/multichat.db")
    if not os.path.exists(sqlite_path):
        log(f"sqlite file not found, skip migration: {sqlite_path}")
        return 0

    sqlite_conn = sqlite3.connect(sqlite_path)
    try:
        s_cur = sqlite_conn.cursor()
        s_cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
        tables = [r[0] for r in s_cur.fetchall()]
        if not tables:
            log("no sqlite tables found, nothing to migrate")
            return 0

        pg_conn = wait_postgres()
        try:
            for t in tables:
                migrate_table(pg_conn, sqlite_conn, t)

            # Normalize model ids for OpenRouter accounts only.
            # This avoids ambiguous autodetect and keeps direct API accounts untouched.
            p_cur = pg_conn.cursor()
            p_cur.execute(
                """
                UPDATE users
                SET llm_class = 'openrouter:' || llm_class
                WHERE llm_class LIKE '%/%'
                  AND llm_class NOT LIKE 'openrouter:%'
                  AND llm_token LIKE 'sk-or-%'
                """
            )

            p_cur.execute("ALTER TABLE users ALTER COLUMN llm_reasoning_eff SET DEFAULT 'medium'")
            p_cur.execute("UPDATE users SET llm_reasoning_eff = 'medium' WHERE llm_reasoning_eff IS NULL")
            sync_postgres_sequences(pg_conn)
            pg_conn.commit()
        finally:
            pg_conn.close()
    finally:
        sqlite_conn.close()

    log("migration completed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
