--
-- PostgreSQL database dump
--

\restrict uk8NMxJbkK0OzfIvLODpDThYtGGI6QqtgGlPYNJJJE6QABATTPET7LSAwpViK6u

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attached_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attached_files (
    id bigint NOT NULL,
    content bytea,
    ts bigint,
    file_name text,
    project_id bigint
);


--
-- Name: attached_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attached_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attached_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chats (
    chat_id bigint NOT NULL,
    chat_description text,
    user_list text,
    parent_msg_id bigint
);


--
-- Name: chats_chat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chats ALTER COLUMN chat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: file_spans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_spans (
    hash text NOT NULL,
    file_id bigint,
    meta_data numeric,
    block_code text
);


--
-- Name: llm_context; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.llm_context (
    actor_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    last_post_id bigint,
    last_timestamp bigint
);


--
-- Name: llm_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.llm_responses (
    response_id bigint NOT NULL,
    actor_id bigint,
    chat_id bigint,
    response_text text,
    "timestamp" bigint,
    triggered_by bigint,
    rql bigint
);


--
-- Name: llm_responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.llm_responses ALTER COLUMN response_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.llm_responses_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: llm_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.llm_usage (
    ts bigint,
    model text,
    sent_tokens bigint,
    used_tokens bigint,
    output_tokens bigint,
    sources_used bigint,
    token_limit bigint,
    token_cost double precision,
    chat_id bigint
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    chat_id bigint,
    user_id bigint,
    message text,
    "timestamp" bigint,
    rql bigint,
    reply_to bigint,
    elapsed double precision
);


--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    project_name text NOT NULL,
    description text,
    local_git text,
    public_git text,
    dependencies text
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quotes (
    quote_id bigint NOT NULL,
    chat_id bigint,
    user_id bigint,
    content text NOT NULL,
    "timestamp" bigint
);


--
-- Name: quotes_quote_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quotes ALTER COLUMN quote_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotes_quote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    session_id text NOT NULL,
    user_id bigint,
    active_chat bigint,
    active_project bigint
);


--
-- Name: user_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_settings (
    user_id bigint NOT NULL,
    search_mode text,
    search_sources text,
    max_search_results bigint,
    from_date text,
    to_date text
);


--
-- Name: user_settings_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_settings ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_settings_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    user_name text,
    llm_class text,
    llm_token text,
    tokens_limit bigint,
    tokens_cost double precision,
    llm_reasoning_eff text DEFAULT 'medium'::text,
    password_hash text,
    salt text
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attached_files attached_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attached_files
    ADD CONSTRAINT attached_files_pkey PRIMARY KEY (id);


--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (chat_id);


--
-- Name: file_spans file_spans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_spans
    ADD CONSTRAINT file_spans_pkey PRIMARY KEY (hash);


--
-- Name: llm_context llm_context_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.llm_context
    ADD CONSTRAINT llm_context_pkey PRIMARY KEY (actor_id, chat_id);


--
-- Name: llm_responses llm_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.llm_responses
    ADD CONSTRAINT llm_responses_pkey PRIMARY KEY (response_id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: quotes quotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT quotes_pkey PRIMARY KEY (quote_id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (session_id);


--
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict uk8NMxJbkK0OzfIvLODpDThYtGGI6QqtgGlPYNJJJE6QABATTPET7LSAwpViK6u


