FROM node:20

# Рабочая директория
WORKDIR /app/frontend

VOLUME /app/frontend
VOLUME /app/logs

# Установка Vue CLI
RUN npm install -g @vue/cli
RUN apt update && apt -y install nano inetutils-ping traceroute

RUN npm install -g @vue/cli-init
RUN npm install mitt
COPY frontend/rtm/start.sh /app/

# Запуск
CMD ["sh", "-c", "/app/start.sh"]

